version: "3.9"

services:
  db:
    image: postgres:15
    container_name: savanna-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable",
      "up"
    ]
    restart: on-failure

  savanna-app:
    build: .
    container_name: savanna-app
    depends_on:
      - db
      - migrate
    environment:
       DATABASE_URL: ${DATABASE_URL}
       AUTH0_DOMAIN: ${AUTH0_DOMAIN}
       AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
       AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
       AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
       AUTH0_MANAGEMENT_API_AUDIENCE: ${AUTH0_MANAGEMENT_API_AUDIENCE}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
