apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-db
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: registry.digitalocean.com/savanna/savanna-app:migrate
          imagePullPolicy: Always
          command:
            [
              "migrate",
              "-path", "/migrations",
              "-database", "postgres://postgres:securepass@savanna-db:5432/savanna?sslmode=disable",
              "up"
            ]
      restartPolicy: OnFailure
