apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-db
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: migrate-with-files
          imagePullPolicy: Never
          command:
            [
              "migrate",
              "-path", "/migrations",
              "-database", "postgres://postgres:securepass@savanna-db:5432/savanna?sslmode=disable",
              "up"
            ]
      restartPolicy: OnFailure
