apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-test-db
spec:
  template:
    spec:
      containers:
        - name: migrate-test
          image: migrate/migrate
          command:
            [
              "migrate",
              "-path", "/migrations",
              "-database", "postgres://postgres:securepass@savanna-db:5432/savanna_test?sslmode=disable",
              "up"
            ]
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      restartPolicy: OnFailure
      volumes:
        - name: migrations
          hostPath:
            path: ./migrations
            type: Directory
