apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-db
spec:
  backoffLimit: 2
  template:
    spec:
      imagePullSecrets:
        - name: do-registry
      containers:
        - name: migrate
          image: migrate/migrate:v4.16.2
          command: ["/bin/sh", "-c"]
          args:
            - migrate -path /migrations -database "$DATABASE_URL" up
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: migration-files
              mountPath: /migrations
      restartPolicy: Never
      volumes:
        - name: migration-files
          configMap:
            name: migration-sql
