apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-db
spec:
  template:
    spec:
      imagePullSecrets:
        - name: do-registry
      containers:
        - name: migrate
          image: migrate/migrate:v4.16.2
          command: ["migrate"]
          args:
            - "-path"
            - "/migrations"
            - "-database"
            - "postgres://postgres:securepass@savanna-db:5432/savanna?sslmode=disable"
            - "up"
          volumeMounts:
            - name: migration-files
              mountPath: /migrations
      restartPolicy: OnFailure
      volumes:
        - name: migration-files
          configMap:
            name: migration-sql
