// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Category struct {
	ID     string    `json:"id"`
	Name   string    `json:"name"`
	Parent *Category `json:"parent,omitempty"`
}

type CategoryInput struct {
	Name     string  `json:"name"`
	ParentID *string `json:"parentID,omitempty"`
}

type Customer struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
}

type CustomerInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Mutation struct {
}

type Order struct {
	ID        string       `json:"id"`
	Customer  *Customer    `json:"customer"`
	OrderDate string       `json:"orderDate"`
	Status    string       `json:"status"`
	Items     []*OrderItem `json:"items"`
}

type OrderInput struct {
	CustomerID string            `json:"customerID"`
	Items      []*OrderItemInput `json:"items"`
}

type OrderItem struct {
	ID       string   `json:"id"`
	Product  *Product `json:"product"`
	Quantity int      `json:"quantity"`
	Price    float64  `json:"price"`
}

type OrderItemInput struct {
	ProductID string  `json:"productID"`
	Quantity  int     `json:"quantity"`
	Price     float64 `json:"price"`
}

type Product struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	Price       float64   `json:"price"`
	Category    *Category `json:"category,omitempty"`
}

type ProductInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Price       float64 `json:"price"`
	CategoryID  *string `json:"categoryID,omitempty"`
}

type Query struct {
}
